name: NumPy Doc Redirect CI Build Sanity
on: [push]
jobs:
# macos_build:
#   runs-on: macos-latest
#   steps:
#   - uses: actions/checkout@v1
#   - uses: actions/setup-python@v1
#     with:
#       python-version: 3.8
#   - name: Install MacOS Dependencies
#     run: |
#         brew update
#         brew upgrade
#         brew install enchant
#         python -m pip install --upgrade pip
#         pip install sphinx sphinx_rtd_theme
#         pip install -r ./requirements.txt
#   - name: Sphinx build
#     run: |
#         val=`ls -alth`
#         echo This is current dir contents $val
#         make clean spelling html
  linuxos_build:
    runs-on: ubuntu-18.04 
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Linux Dependencies
      run: |
          export SETUPTOOLS_USE_DISTUTILS=stdlib
          sudo apt-get update -y && sudo apt-get install -y build-essential make libenchant-dev enchant git latexmk texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-luatex texlive-xetex dialog apt-utils && sudo apt-get autoremove && sudo apt-get clean
          python3 -m pip install --upgrade setuptools
          python3 -m pip install -r beta/docs/requirements.txt
    - name: Sphinx build
      run: |
          make clean spelling html latexpdf
