name: NumPy Doc Redirect CI Build Sanity
on: [push]
jobs:
  macos_build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
          brew update
          brew upgrade
          brew install enchant
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme
          pip install -r ./requirements.txt
    - name: Sphinx build
      run: |
          val=`ls -alth`
          echo This is current dir contents $val
          make -C docs/ clean spelling html
